name: CI-CD BlueGreen

on:
  push:
    branches:
      - main

env:
  IMAGE: ""  # Will be set dynamically after build

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/myapp:${GITHUB_SHA,,}  # lowercase tag
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t $IMAGE .
          docker push $IMAGE

  trivy-scan:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.31.0
        with:
          image-ref: ${{ env.IMAGE }}
          format: 'table'
          exit-code: '1'  # Fail if HIGH/CRITICAL vulnerabilities found

  deploy-green:
    runs-on: ubuntu-latest
    needs: trivy-scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set AKS context
        uses: azure/aks-set-context@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Deploy green version
        run: |
          kubectl apply -f k8s/green-deploy.yaml
          kubectl rollout status deploy/myapp-green -w

      - name: Get LoadBalancer IP
        id: lb
        run: |
          INGRESS_HOST=$(kubectl get svc myapp-svc -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "INGRESS_HOST=$INGRESS_HOST" >> $GITHUB_ENV
          echo "Ingress host: $INGRESS_HOST"

      - name: Smoke test
        run: |
          curl -f http://$INGRESS_HOST/health || exit 1

      - name: Switch service to green
        run: |
          kubectl patch svc myapp-svc -p "{\"spec\":{\"selector\":{\"app\":\"myapp\",\"version\":\"green\"}}}"
